import jsPDF from "jspdf";

interface ClaimPdfParams {
  extracted?: {
    medicalSummary: {
      admissionDate?: string;
      dischargeDate?: string;
      primaryDiagnosis?: string;
      secondaryDiagnoses?: string[];
      proceduresPerformed?: string[];
      medicationsAtDischarge?: { name: string; dosage?: string; frequency?: string; duration?: string }[];
      followUpInstructions?: string[];
      keyFindings?: string[];
      allergiesNoted?: string[];
      dietaryInstructions?: string[];
      activityRestrictions?: string[];
    };
    insuranceClaim: {
      patientName?: string;
      patientAge?: string;
      patientGender?: string;
      hospitalName?: string;
      hospitalAddress?: string;
      admissionDate?: string;
      dischargeDate?: string;
      daysOfStay?: string;
      admissionType?: string;
      primaryDiagnosis?: string;
      icdCodes?: string[];
      procedureCodes?: string[];
      procedureDescriptions?: string[];
      treatingDoctorName?: string;
      treatingDoctorRegistration?: string;
      roomType?: string;
      billingItems?: { item: string; amount?: string }[];
      totalBillAmount?: string;
      preAuthorizationNumber?: string;
    };
    confidence: string;
  };
  insurance: {
    insuranceCompany: string;
    policyNumber: string;
    claimType: string;
    policyHolderName: string;
    policyHolderRelation: string;
    bankName: string;
    bankAccountNumber: string;
    bankIfsc: string;
    tpaName: string;
  };
  uploadedCategories: string[];
}

const MARGIN = 20;
const PAGE_WIDTH = 210;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

export async function generateClaimPdf(params: ClaimPdfParams) {
  const { extracted, insurance, uploadedCategories } = params;
  const ic = extracted?.insuranceClaim;
  const ms = extracted?.medicalSummary;
  const doc = new jsPDF();

  let y = MARGIN;

  const checkPage = (needed: number) => {
    if (y + needed > 280) {
      doc.addPage();
      y = MARGIN;
    }
  };

  const addTitle = (text: string) => {
    checkPage(12);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(text, MARGIN, y);
    y += 8;
    doc.setDrawColor(59, 130, 246);
    doc.setLineWidth(0.5);
    doc.line(MARGIN, y, MARGIN + CONTENT_WIDTH, y);
    y += 6;
  };

  const addField = (label: string, value: string | undefined | null) => {
    checkPage(8);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text(label, MARGIN, y);
    doc.setTextColor(0);
    doc.setFont("helvetica", "bold");
    const val = value || "___________________";
    doc.text(val, MARGIN + 60, y);
    doc.setFont("helvetica", "normal");
    y += 6;
  };

  const addListItem = (text: string) => {
    checkPage(7);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0);
    const lines = doc.splitTextToSize(`• ${text}`, CONTENT_WIDTH - 5);
    doc.text(lines, MARGIN + 5, y);
    y += lines.length * 4.5;
  };

  // ═══ HEADER ═══
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(59, 130, 246);
  doc.text("HEALTH INSURANCE CLAIM FORM", MARGIN, y);
  y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`Generated by Vyana · ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}`, MARGIN, y);
  y += 4;
  doc.setTextColor(200, 0, 0);
  doc.setFontSize(8);
  doc.text("This is an auto-generated form. Verify all details before submitting to your insurer.", MARGIN, y);
  doc.setTextColor(0);
  y += 10;

  // ═══ SECTION 1: INSURANCE DETAILS ═══
  addTitle("1. Insurance Information");
  addField("Insurance Company", insurance.insuranceCompany);
  addField("Policy Number", insurance.policyNumber);
  addField("Claim Type", insurance.claimType ? insurance.claimType.charAt(0).toUpperCase() + insurance.claimType.slice(1) : "");
  addField("TPA Name", insurance.tpaName);
  addField("Policy Holder", insurance.policyHolderName);
  addField("Relation", insurance.policyHolderRelation);
  if (insurance.claimType === "reimbursement") {
    addField("Bank Name", insurance.bankName);
    addField("Account Number", insurance.bankAccountNumber);
    addField("IFSC Code", insurance.bankIfsc);
  }
  y += 4;

  // ═══ SECTION 2: PATIENT DETAILS ═══
  addTitle("2. Patient Details");
  addField("Patient Name", ic?.patientName);
  addField("Age", ic?.patientAge);
  addField("Gender", ic?.patientGender);
  y += 4;

  // ═══ SECTION 3: HOSPITAL DETAILS ═══
  addTitle("3. Hospital & Admission Details");
  addField("Hospital Name", ic?.hospitalName);
  addField("Hospital Address", ic?.hospitalAddress);
  addField("Admission Date", ic?.admissionDate);
  addField("Discharge Date", ic?.dischargeDate);
  addField("Days of Stay", ic?.daysOfStay);
  addField("Admission Type", ic?.admissionType);
  addField("Room Type", ic?.roomType);
  addField("Pre-Auth #", ic?.preAuthorizationNumber);
  y += 4;

  // ═══ SECTION 4: DIAGNOSIS & PROCEDURES ═══
  addTitle("4. Diagnosis & Procedures");
  addField("Primary Diagnosis", ic?.primaryDiagnosis);
  if (ic?.icdCodes?.length) addField("ICD Codes", ic.icdCodes.join(", "));
  if (ic?.procedureDescriptions?.length) {
    checkPage(6);
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text("Procedures:", MARGIN, y);
    y += 5;
    ic.procedureDescriptions.forEach(p => addListItem(p));
  }
  y += 4;

  // ═══ SECTION 5: TREATING DOCTOR ═══
  addTitle("5. Treating Doctor");
  addField("Doctor Name", ic?.treatingDoctorName);
  addField("Registration #", ic?.treatingDoctorRegistration);
  y += 4;

  // ═══ SECTION 6: BILLING ═══
  addTitle("6. Billing Summary");
  if (ic?.billingItems?.length) {
    checkPage(10);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("Item", MARGIN, y);
    doc.text("Amount (₹)", MARGIN + 120, y);
    y += 5;
    doc.setDrawColor(200);
    doc.line(MARGIN, y - 1, MARGIN + CONTENT_WIDTH, y - 1);
    doc.setFont("helvetica", "normal");
    ic.billingItems.forEach(b => {
      checkPage(6);
      doc.text(b.item, MARGIN, y);
      doc.text(b.amount || "—", MARGIN + 120, y);
      y += 5;
    });
    doc.setDrawColor(0);
    doc.line(MARGIN, y, MARGIN + CONTENT_WIDTH, y);
    y += 5;
  }
  addField("Total Bill Amount", ic?.totalBillAmount ? `Rs. ${ic.totalBillAmount}` : "");
  y += 4;

  // ═══ SECTION 7: MEDICAL SUMMARY ═══
  doc.addPage();
  y = MARGIN;

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(59, 130, 246);
  doc.text("MEDICAL SUMMARY", MARGIN, y);
  y += 5;
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text("For future doctor visits — extracted from discharge summary", MARGIN, y);
  doc.setTextColor(0);
  y += 10;

  addTitle("Diagnosis & Findings");
  addField("Primary Diagnosis", ms?.primaryDiagnosis);
  if (ms?.secondaryDiagnoses?.length) {
    ms.secondaryDiagnoses.forEach(d => addListItem(d));
  }
  if (ms?.keyFindings?.length) {
    checkPage(6);
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text("Key Findings:", MARGIN, y);
    doc.setTextColor(0);
    y += 5;
    ms.keyFindings.forEach(f => addListItem(f));
  }
  y += 4;

  if (ms?.medicationsAtDischarge?.length) {
    addTitle("Medications at Discharge");
    ms.medicationsAtDischarge.forEach(med => {
      const parts = [med.name, med.dosage, med.frequency, med.duration].filter(Boolean).join(" · ");
      addListItem(parts);
    });
    y += 4;
  }

  if (ms?.followUpInstructions?.length) {
    addTitle("Follow-up Instructions");
    ms.followUpInstructions.forEach(f => addListItem(f));
    y += 4;
  }

  if (ms?.dietaryInstructions?.length) {
    addTitle("Dietary Instructions");
    ms.dietaryInstructions.forEach(d => addListItem(d));
    y += 4;
  }

  if (ms?.activityRestrictions?.length) {
    addTitle("Activity Restrictions");
    ms.activityRestrictions.forEach(a => addListItem(a));
    y += 4;
  }

  if (ms?.allergiesNoted?.length) {
    addTitle("Allergies");
    ms.allergiesNoted.forEach(a => addListItem(a));
    y += 4;
  }

  // ═══ DOCUMENT CHECKLIST ═══
  addTitle("Document Checklist");
  const allCategories = [
    { id: "discharge_summary", label: "Discharge Summary" },
    { id: "hospital_bill", label: "Final Hospital Bill" },
    { id: "investigation_reports", label: "Investigation Reports" },
    { id: "prescriptions", label: "Prescriptions" },
    { id: "insurance_claim_form", label: "Insurance Claim Form" },
    { id: "admission_note", label: "Admission Note" },
    { id: "id_proof", label: "ID Proof" },
    { id: "insurance_card", label: "Insurance Card" },
  ];

  allCategories.forEach(cat => {
    checkPage(6);
    const has = uploadedCategories.includes(cat.id);
    doc.setFontSize(9);
    doc.text(has ? "[✓]" : "[ ]", MARGIN, y);
    doc.text(cat.label, MARGIN + 10, y);
    y += 5;
  });

  // ═══ SIGNATURES ═══
  y += 10;
  checkPage(30);
  doc.setDrawColor(150);
  doc.line(MARGIN, y, MARGIN + 60, y);
  doc.line(MARGIN + 90, y, MARGIN + CONTENT_WIDTH, y);
  y += 5;
  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text("Patient / Policyholder Signature", MARGIN, y);
  doc.text("Date", MARGIN + 90, y);
  y += 10;
  doc.line(MARGIN, y, MARGIN + 60, y);
  y += 5;
  doc.text("Hospital Seal & Signature", MARGIN, y);

  // ═══ FOOTER ═══
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount} · Generated by Vyana · This is not an official insurance document`,
      PAGE_WIDTH / 2, 292, { align: "center" }
    );
  }

  doc.save(`Vyana_Insurance_Claim_${new Date().toISOString().slice(0, 10)}.pdf`);
}
