import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import {
  Loader2, Sparkles, AlertTriangle, TrendingUp, Pill, FileText,
  Share2, Copy, CheckCircle2, Heart, Brain, Stethoscope,
  ArrowUp, ArrowDown, Minus, Activity,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

interface Briefing {
  patient_overview: { key_conditions: string[]; summary: string };
  key_trends: Array<{ vital: string; direction: string; detail: string; concern_level: string }>;
  current_medications: Array<{ name: string; status: string; note?: string }>;
  red_flags: Array<{ flag: string; severity: string; detail: string }>;
  recent_changes: string[];
  soap_note: { subjective: string; objective: string; assessment: string; plan: string };
  medication_correlations: Array<{ observation: string; confidence: string; supporting_data: string }>;
  disclaimer?: string;
}

const PatientBriefing = () => {
  const [briefing, setBriefing] = useState<Briefing | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  const generateBriefing = async () => {
    setIsLoading(true);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) return;

      const { data: patient } = await supabase
        .from("patients")
        .select("id, national_health_id, name, age")
        .eq("user_id", session.user.id)
        .maybeSingle();

      if (!patient) {
        toast({ title: "Complete your profile first", variant: "destructive" });
        return;
      }

      // Fetch all patient data in parallel
      const [consultationsRes, recordsRes, vitalsRes, medsRes] = await Promise.all([
        patient.national_health_id
          ? supabase.from("consultations").select("*").eq("patient_national_health_id", patient.national_health_id).order("created_at", { ascending: false }).limit(10)
          : Promise.resolve({ data: [] }),
        supabase.from("health_records").select("file_name, ai_summary").eq("patient_id", patient.id).order("uploaded_at", { ascending: false }).limit(10),
        supabase.from("vital_history").select("*").eq("patient_id", patient.id).order("recorded_at", { ascending: true }),
        supabase.from("medication_reminders").select("*").eq("patient_id", patient.id),
      ]);

      const { data, error } = await supabase.functions.invoke("clinical-briefing", {
        body: {
          patientHealthId: patient.national_health_id,
          consultations: consultationsRes.data || [],
          healthRecordSummaries: recordsRes.data || [],
          vitalHistory: vitalsRes.data || [],
          medicationReminders: medsRes.data || [],
        },
      });

      if (error) throw error;
      setBriefing(data);
    } catch (err: any) {
      console.error("Briefing error:", err);
      toast({ title: "Error", description: "Failed to generate briefing", variant: "destructive" });
    } finally {
      setIsLoading(false);
    }
  };

  const briefingToText = (): string => {
    if (!briefing) return "";
    let text = `🏥 *My Health Briefing*\n\n`;
    text += `*Overview:* ${briefing.patient_overview.summary}\n`;
    if (briefing.patient_overview.key_conditions.length > 0) {
      text += `*Conditions:* ${briefing.patient_overview.key_conditions.join(", ")}\n`;
    }
    if (briefing.red_flags.length > 0) {
      text += `\n⚠️ *Flags:*\n`;
      briefing.red_flags.forEach(rf => { text += `• ${rf.flag}: ${rf.detail}\n`; });
    }
    if (briefing.current_medications.length > 0) {
      text += `\n💊 *Current Medications:*\n`;
      briefing.current_medications.filter(m => m.status === "active").forEach(m => {
        text += `• ${m.name}${m.note ? ` — ${m.note}` : ""}\n`;
      });
    }
    if (briefing.key_trends.length > 0) {
      text += `\n📊 *Key Trends:*\n`;
      briefing.key_trends.forEach(t => { text += `• ${t.vital}: ${t.direction} — ${t.detail}\n`; });
    }
    text += `\n_Generated by Vyana · ${new Date().toLocaleDateString("en-IN")}_`;
    text += `\n_AI-generated summary. Please verify clinically._`;
    return text;
  };

  const shareViaWhatsApp = () => {
    const text = briefingToText();
    const url = `https://wa.me/?text=${encodeURIComponent(text)}`;
    window.open(url, "_blank");
  };

  const copyToClipboard = async () => {
    const text = briefingToText();
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    toast({ title: "Copied to clipboard" });
  };

  const dirIcon = (d: string) => {
    if (d === "increasing") return <ArrowUp className="h-3 w-3 text-destructive" />;
    if (d === "decreasing") return <ArrowDown className="h-3 w-3 text-blue-500" />;
    if (d === "stable") return <Minus className="h-3 w-3 text-green-600" />;
    return <Activity className="h-3 w-3 text-yellow-500" />;
  };

  return (
    <div className="animate-fade-in">
      <section className="px-5 pt-8 pb-4">
        <h1 className="text-[28px] font-extrabold leading-[1.08] tracking-[-0.03em] text-foreground">
          My Briefing
        </h1>
        <p className="text-[14px] text-muted-foreground leading-relaxed mt-2">
          Generate your clinical summary to share with any doctor — instantly.
        </p>
      </section>

      {/* Generate button */}
      {!briefing && (
        <section className="px-5 pb-6">
          <div className="rounded-xl border border-primary/20 bg-primary/5 p-6 text-center">
            <div className="h-14 w-14 rounded-2xl bg-primary/10 flex items-center justify-center mx-auto mb-4">
              <Stethoscope className="h-7 w-7 text-primary" />
            </div>
            <h2 className="text-lg font-bold text-foreground mb-2">Doctor-Ready Summary</h2>
            <p className="text-sm text-muted-foreground mb-5 max-w-xs mx-auto">
              AI analyzes your records, vitals, and medications to create a summary any doctor can read in 30 seconds.
            </p>
            <Button
              onClick={generateBriefing}
              disabled={isLoading}
              className="w-full max-w-xs"
              size="lg"
            >
              {isLoading ? (
                <><Loader2 className="h-4 w-4 animate-spin mr-2" /> Generating...</>
              ) : (
                <><Sparkles className="h-4 w-4 mr-2" /> Generate My Briefing</>
              )}
            </Button>
          </div>
        </section>
      )}

      {/* Loading state */}
      {isLoading && !briefing && (
        <section className="px-5 pb-6">
          <div className="rounded-xl border border-border bg-card p-6 text-center">
            <Loader2 className="h-8 w-8 animate-spin text-primary mx-auto mb-3" />
            <p className="text-sm text-muted-foreground">
              Analyzing your health records, vitals, and medications...
            </p>
          </div>
        </section>
      )}

      {/* Briefing display */}
      {briefing && (
        <>
          {/* Share actions */}
          <section className="px-5 pb-4">
            <div className="flex gap-2">
              <Button onClick={shareViaWhatsApp} variant="outline" className="flex-1 gap-2">
                <Share2 className="h-4 w-4" />
                Share via WhatsApp
              </Button>
              <Button onClick={copyToClipboard} variant="outline" className="gap-2">
                {copied ? <CheckCircle2 className="h-4 w-4 text-green-600" /> : <Copy className="h-4 w-4" />}
              </Button>
              <Button onClick={generateBriefing} variant="outline" size="icon" disabled={isLoading}>
                {isLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
              </Button>
            </div>
          </section>

          {/* Overview */}
          <section className="px-5 pb-4">
            <div className="rounded-xl border border-border bg-card p-4">
              <div className="flex items-center gap-2 mb-2">
                <Heart className="h-4 w-4 text-primary" />
                <h3 className="text-[14px] font-bold text-foreground">Overview</h3>
              </div>
              <p className="text-[13px] text-foreground leading-relaxed">{briefing.patient_overview.summary}</p>
              {briefing.patient_overview.key_conditions.length > 0 && (
                <div className="flex flex-wrap gap-1.5 mt-3">
                  {briefing.patient_overview.key_conditions.map((c, i) => (
                    <Badge key={i} variant="secondary" className="text-[11px]">{c}</Badge>
                  ))}
                </div>
              )}
            </div>
          </section>

          {/* Red flags */}
          {briefing.red_flags.length > 0 && (
            <section className="px-5 pb-4">
              <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-4">
                <div className="flex items-center gap-2 mb-3">
                  <AlertTriangle className="h-4 w-4 text-destructive" />
                  <h3 className="text-[14px] font-bold text-destructive">Flags for Doctor</h3>
                </div>
                <div className="space-y-2">
                  {briefing.red_flags.map((rf, i) => (
                    <div key={i} className={`rounded-lg p-3 ${rf.severity === "critical" ? "bg-destructive/10 border border-destructive/20" : "bg-yellow-500/10 border border-yellow-500/20"}`}>
                      <p className="text-[13px] font-medium text-foreground">{rf.flag}</p>
                      <p className="text-[11px] text-muted-foreground mt-0.5">{rf.detail}</p>
                    </div>
                  ))}
                </div>
              </div>
            </section>
          )}

          {/* Medications */}
          {briefing.current_medications.length > 0 && (
            <section className="px-5 pb-4">
              <div className="rounded-xl border border-border bg-card p-4">
                <div className="flex items-center gap-2 mb-3">
                  <Pill className="h-4 w-4 text-primary" />
                  <h3 className="text-[14px] font-bold text-foreground">Medications</h3>
                </div>
                <div className="space-y-1.5">
                  {briefing.current_medications.map((m, i) => (
                    <div key={i} className="flex items-center gap-2 rounded-lg bg-muted/50 px-3 py-2">
                      <span className={`h-2 w-2 rounded-full ${m.status === "active" ? "bg-green-500" : m.status === "recently_started" ? "bg-blue-500" : "bg-muted-foreground"}`} />
                      <span className="text-[13px] text-foreground flex-1">{m.name}</span>
                      <Badge variant="outline" className="text-[9px]">{m.status.replace("_", " ")}</Badge>
                    </div>
                  ))}
                </div>
              </div>
            </section>
          )}

          {/* Trends */}
          {briefing.key_trends.length > 0 && (
            <section className="px-5 pb-4">
              <div className="rounded-xl border border-border bg-card p-4">
                <div className="flex items-center gap-2 mb-3">
                  <TrendingUp className="h-4 w-4 text-primary" />
                  <h3 className="text-[14px] font-bold text-foreground">Key Trends</h3>
                </div>
                <div className="space-y-2">
                  {briefing.key_trends.map((t, i) => (
                    <div key={i} className="flex items-start gap-2 rounded-lg bg-muted/50 px-3 py-2">
                      {dirIcon(t.direction)}
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2">
                          <span className="text-[13px] font-medium text-foreground">{t.vital}</span>
                          {t.concern_level === "action_needed" && (
                            <Badge variant="destructive" className="text-[9px]">action needed</Badge>
                          )}
                          {t.concern_level === "monitor" && (
                            <Badge variant="outline" className="text-[9px] border-yellow-500/30 text-yellow-600">monitor</Badge>
                          )}
                        </div>
                        <p className="text-[11px] text-muted-foreground">{t.detail}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </section>
          )}

          {/* Recent changes */}
          {briefing.recent_changes.length > 0 && (
            <section className="px-5 pb-4">
              <div className="rounded-xl border border-border bg-card p-4">
                <div className="flex items-center gap-2 mb-3">
                  <FileText className="h-4 w-4 text-primary" />
                  <h3 className="text-[14px] font-bold text-foreground">Recent Changes</h3>
                </div>
                <ul className="space-y-1">
                  {briefing.recent_changes.map((c, i) => (
                    <li key={i} className="text-[12px] text-foreground flex gap-2 items-start">
                      <span className="text-primary mt-0.5">•</span>{c}
                    </li>
                  ))}
                </ul>
              </div>
            </section>
          )}

          {/* SOAP Note */}
          <section className="px-5 pb-4">
            <div className="rounded-xl border border-border bg-card p-4">
              <div className="flex items-center gap-2 mb-3">
                <Brain className="h-4 w-4 text-primary" />
                <h3 className="text-[14px] font-bold text-foreground">SOAP Note</h3>
              </div>
              <div className="space-y-3">
                {[
                  { label: "S — Subjective", value: briefing.soap_note.subjective },
                  { label: "O — Objective", value: briefing.soap_note.objective },
                  { label: "A — Assessment", value: briefing.soap_note.assessment },
                  { label: "P — Plan", value: briefing.soap_note.plan },
                ].map((s, i) => (
                  <div key={i}>
                    <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider mb-0.5">{s.label}</p>
                    <p className="text-[12px] text-foreground leading-relaxed">{s.value}</p>
                  </div>
                ))}
              </div>
            </div>
          </section>

          {/* Medication correlations */}
          {briefing.medication_correlations.length > 0 && (
            <section className="px-5 pb-4">
              <div className="rounded-xl border border-border bg-card p-4">
                <div className="flex items-center gap-2 mb-3">
                  <Pill className="h-4 w-4 text-primary" />
                  <h3 className="text-[14px] font-bold text-foreground">Medication-Lab Correlations</h3>
                </div>
                <div className="space-y-2">
                  {briefing.medication_correlations.map((c, i) => (
                    <div key={i} className="rounded-lg border border-border p-3">
                      <div className="flex items-center gap-2 mb-1">
                        <p className="text-[12px] font-medium text-foreground flex-1">{c.observation}</p>
                        <Badge variant="outline" className={`text-[9px] ${c.confidence === "high" ? "border-green-500/30 text-green-600" : c.confidence === "medium" ? "border-yellow-500/30 text-yellow-600" : ""}`}>
                          {c.confidence}
                        </Badge>
                      </div>
                      <p className="text-[11px] text-muted-foreground">{c.supporting_data}</p>
                    </div>
                  ))}
                </div>
              </div>
            </section>
          )}

          {/* Disclaimer */}
          {briefing.disclaimer && (
            <section className="px-5 pb-8">
              <p className="text-[10px] text-muted-foreground italic text-center">{briefing.disclaimer}</p>
            </section>
          )}
        </>
      )}
    </div>
  );
};

export default PatientBriefing;
